[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyEDAkit"
version = "0.1.4"
description = "A toolkit for exploratory data analysis in Python"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Alberto Biscalchin", email = "biscalchin.mau.se@gmail.com" },
    { name = "Marco Schivo", email = "marcoschivo1@gmail.com" }
]
keywords = ["data analysis", "EDA", "machine learning"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Information Analysis"
]
dependencies = [
    "matplotlib>=3.8.4",
    "MiniSom>=2.3.3",
    "networkx>=3.3",
    "numpy>=2.2.2",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.1",
    "seaborn>=0.13.2"
]
requires-python = ">=3.12"

[project.urls]
homepage = "https://github.com/zkivo/pyEDAkit"
repository = "https://github.com/zkivo/pyEDAkit"

[tool.setuptools.packages.find]
include = ["pyEDAkit*"]
exclude = ["datasets", "examples", "figures"]
